#!/usr/bin/expect -f
set force_conservative 0  ;
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}
set IP [lindex $argv 0]
set PWD [lindex $argv 1]
set CMD [lindex $argv 2]
set NUM [lindex $argv 3]
set timeout -1
spawn $env(SHELL)
match_max 100000
expect  "*# "
send -- "ssh root@$IP 'bash -s '<$CMD $NUM\r"
expect "*password: "
send -- "$PWD\r"
expect  "*# "
send -- "exit\r"
expect eof
